
# Use the base image directly, you can replace the FROM on the first line of this
# file with this one instead. You can also manually install Elixir, but that requires
# a bit more work.
FROM elixir:1.15.4
